version: "3.7"
services:
  app_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root